const Images = {
  header_logo: "/assets/images/logo.png",
  worksBg: "/assets/images/worksBg.png",
  google: "/assets/images/google.png",
  fb: "/assets/images/fb.png",
  apple: "/assets/images/apple.png",
  flogo: "/assets/images/flogo.png",
  success: "/assets/images/success.png",
  chatico: "/assets/images/chatico.svg",
  BellSimple: "/assets/images/BellSimple.svg",
  verified: "/assets/images/verified.svg",
  share: "/assets/images/share.svg",
  copy: "/assets/images/copy.svg",
  Location: "/assets/images/Location.svg",
  Heart: "/assets/images/Heart.svg",
  reply: "/assets/images/reply.svg",
  building: "/assets/images/building.png",
  profile: "/assets/images/profile.png",
  Facebook: "/assets/images/Facebook.svg",
  Instagram: "/assets/images/Instagram.svg",
  Yt: "/assets/images/Yt.svg",
  Linkedin: "/assets/images/Linkedin.svg",
  doller: "/assets/images/dollar-circle.png",
  globe: "/assets/images/globe.png",
  laptop: "/assets/images/laptop.png",
  Phone: "/assets/images/Phone.png",
  Linkedin1: "/assets/images/linkedin.png",
  Fb1: "/assets/images/facebook.png",
  logo_white: "/assets/images/logo_white.svg",
  fb_white: "/assets/images/fb_white.svg",
  twitter: "/assets/images/twitter.svg",
  insta_white: "/assets/images/insta_white.svg",

  icon1: "/assets/images/icon1.png",
  icon2: "/assets/images/icon2.png",
  icon3: "/assets/images/icon3.png",
  icon4: "/assets/images/icon4.png",
  icon5: "/assets/images/icon5.png",
};

export default Images;
